name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: mxcl/xcodebuild@v1
        with:
          xcode: 13
          scheme: XPTouchBar
          action: test
          configuration: Release
          code-coverage: true
